#Que use la imagen de node version 18 con la version de linux alpine 3.15
FROM node:18-alpine3.15

# Set working directory on container
RUN mkdir -p /var/www/pokedex
WORKDIR /var/www/pokedex

# Copiar todo el contenido del directorio root de la aplicacion al workdir
COPY . ./var/www/pokedex
COPY package.json tsconfig.json tsconfig.build.json /var/www/pokedex/
RUN yarn install --prod
RUN yarn build


# Dar permiso para ejecutar la applicación
RUN adduser --disabled-password pokeuser
RUN chown -R pokeuser:pokeuser /var/www/pokedex
USER pokeuser

# Limpiar el caché
RUN yarn cache clean --force

EXPOSE 3000

CMD [ "yarn","start" ]